### ISSUE TITLE
MuSTA without short-reads

### ISSUE THREAD

**Issue by azodichr** [shinichinamba/MuSTA#4]
When I try to run MuSTA with only the IsoSeq long-reads in the input file, I get this error:

```
Error: The 'short_read' field of the config file must be specified for all samples listed in the 'general' field.
Backtrace:
    █
 1. ├─base::source(src$parse_config.R)
 2. │ ├─base::withVisible(eval(ei, envir))
 3. │ └─base::eval(ei, envir)
 4. │   └─base::eval(ei, envir)
 5. └─purrr::walk2(...)
 6.   └─purrr::map2(.x, .y, .f, ...)
 7.     └─global::.f(.x[[i]], .y[[i]], ...)
Execution halted
```

I've tried removing the "short_read_1" and "short_read_2" columns from the input file entirely and I've tried keeping those column names, but leaving the columns empty, but get this error either way. Is there a flag I need to provide to signal long-read only mode?

**Comment by shinichinamba** [comment]
Unfortunately, MuSTA currently requires short_read_1 and short_read_2 not to contain any missing values.
I'm concerned about the quality of SQANTI filter as its performance without short-read expression data was not evaluated in its original paper.
Therefore, I recommend to use MuSTA with short-read data unless you don't have them, though I'm planning to modify this behavior in the next update.

**Comment by azodichr** [comment]
Thanks for the recommendation. I look forward to that being an option in the future!
